project:
  type: book

css: styles/text.css
number-sections: false
lang: zh
cover-image: images/cover.jpg
format:
  html:
    theme: cosmo
    toc: false

book:
  title: "药娘的天空"
  author: "乱世银娘"
  date: "2017/3/30"
  sidebar:
    collapse-level: -1
  chapters:
    - index.md
    - part: text/1/0.md
      chapters:
        - text/1/1.md
        - text/1/2.md
        - text/1/3.md
        - text/1/4.md
        - text/1/5.md
        - text/1/6.md
        - text/1/7.md
        - text/1/8.md
        - text/1/9.md
        - text/1/10.md
        - text/1/11.md
        - text/1/12.md
        - text/1/13.md
        - text/1/14.md
        - text/1/15.md
        - text/1/16.md
        - text/1/17.md
        - text/1/18.md
        - text/1/19.md
        - text/1/20.md
        - text/1/21.md
        - text/1/22.md
        - text/1/23.md
        - text/1/24.md
        - text/1/25.md
        - text/1/26.md
        - text/1/27.md
        - text/1/28.md
        - text/1/29.md
        - text/1/30.md
        - text/1/31.md
        - text/1/32.md
        - text/1/33.md
        - text/1/34.md
        - text/1/35.md
        - text/1/36.md
        - text/1/37.md
        - text/1/38.md
        - text/1/39.md
        - text/1/40.md
        - text/1/41.md
        - text/1/42.md
        - text/1/43.md
        - text/1/44.md
        - text/1/45.md
        - text/1/46.md
        - text/1/47.md
        - text/1/48.md
        - text/1/49.md
        - text/1/50.md
        - text/1/51.md
        - text/1/52.md
        - text/1/53.md
        - text/1/54.md
        - text/1/55.md
        - text/1/56.md
        - text/1/57.md
        - text/1/58.md
        - text/1/59.md
        - text/1/60.md
    - part: text/2/0.md
      chapters:
        - text/2/61.md
        - text/2/62.md
        - text/2/63.md
        - text/2/64.md
        - text/2/65.md
        - text/2/66.md
        - text/2/67.md
        - text/2/68.md
        - text/2/69.md
        - text/2/70.md
        - text/2/71.md
        - text/2/72.md
        - text/2/73.md
        - text/2/74.md
        - text/2/75.md
        - text/2/76.md
        - text/2/77.md
        - text/2/78.md
        - text/2/79.md
        - text/2/80.md
        - text/2/81.md
        - text/2/82.md
        - text/2/83.md
        - text/2/84.md
        - text/2/85.md
        - text/2/86.md
        - text/2/87.md
        - text/2/88.md
        - text/2/89.md
        - text/2/90.md
        - text/2/91.md
        - text/2/92.md
        - text/2/93.md
        - text/2/94.md
        - text/2/95.md
        - text/2/96.md
        - text/2/97.md
        - text/2/98.md
        - text/2/99.md
        - text/2/100.md
        - text/2/101.md
        - text/2/102.md
        - text/2/103.md
        - text/2/104.md
        - text/2/105.md
        - text/2/106.md
        - text/2/107.md
        - text/2/108.md
        - text/2/109.md
        - text/2/110.md
        - text/2/111.md
        - text/2/112.md
        - text/2/113.md
        - text/2/114.md
        - text/2/115.md
        - text/2/116.md
        - text/2/117.md
        - text/2/118.md
        - text/2/119.md
        - text/2/120.md
        - text/2/121.md
        - text/2/122.md
        - text/2/123.md
        - text/2/124.md
        - text/2/125.md
        - text/2/126.md
        - text/2/127.md
        - text/2/128.md
        - text/2/129.md
        - text/2/130.md
        - text/2/131.md
        - text/2/132.md
        - text/2/133.md
        - text/2/134.md
        - text/2/135.md
        - text/2/136.md
        - text/2/137.md
        - text/2/138.md
        - text/2/139.md
        - text/2/140.md
        - text/2/141.md
        - text/2/142.md
        - text/2/143.md
        - text/2/144.md
        - text/2/145.md
        - text/2/146.md
        - text/2/147.md
        - text/2/148.md
        - text/2/149.md
        - text/2/150.md
        - text/2/151.md
        - text/2/152.md
        - text/2/153.md
        - text/2/154.md
        - text/2/155.md
        - text/2/156.md
        - text/2/157.md
        - text/2/158.md
        - text/2/159.md
        - text/2/160.md
        - text/2/161.md
        - text/2/162.md
        - text/2/163.md
        - text/2/164.md
        - text/2/165.md
        - text/2/166.md
        - text/2/167.md
        - text/2/168.md
        - text/2/169.md
        - text/2/170.md
        - text/2/171.md
        - text/2/172.md
        - text/2/173.md
        - text/2/174.md
        - text/2/175.md
        - text/2/176.md
        - text/2/177.md
        - text/2/178.md
        - text/2/179.md
        - text/2/180.md
        - text/2/181.md
        - text/2/182.md
        - text/2/183.md
        - text/2/184.md
        - text/2/185.md
        - text/2/186.md
        - text/2/187.md
        - text/2/188.md
        - text/2/189.md
        - text/2/190.md
        - text/2/191.md
        - text/2/192.md
        - text/2/193.md
        - text/2/194.md
        - text/2/195.md
        - text/2/196.md
        - text/2/197.md
        - text/2/198.md
        - text/2/199.md
        - text/2/200.md
    - part: text/3/0.md
      chapters:
        - text/3/201.md
        - text/3/202.md
        - text/3/203.md
        - text/3/204.md
        - text/3/205.md
        - text/3/206.md
        - text/3/207.md
        - text/3/208.md
        - text/3/209.md
        - text/3/210.md
        - text/3/211.md
        - text/3/212.md
        - text/3/213.md
        - text/3/214.md
        - text/3/215.md
        - text/3/216.md
        - text/3/217.md
        - text/3/218.md
        - text/3/219.md
        - text/3/220.md
        - text/3/221.md
        - text/3/222.md
        - text/3/223.md
        - text/3/224.md
        - text/3/225.md
        - text/3/226.md
        - text/3/227.md
        - text/3/228.md
        - text/3/229.md
        - text/3/230.md
        - text/3/231.md
        - text/3/232.md
        - text/3/233.md
        - text/3/234.md
        - text/3/235.md
        - text/3/236.md
        - text/3/237.md
        - text/3/238.md
        - text/3/239.md
        - text/3/240.md
        - text/3/241.md
        - text/3/242.md
        - text/3/243.md
        - text/3/244.md
        - text/3/245.md
        - text/3/246.md
        - text/3/247.md
        - text/3/248.md
        - text/3/249.md
        - text/3/250.md
        - text/3/251.md
        - text/3/252.md
        - text/3/253.md
        - text/3/254.md
        - text/3/255.md
        - text/3/256.md
        - text/3/257.md
        - text/3/258.md
        - text/3/259.md
        - text/3/260.md
        - text/3/261.md
        - text/3/262.md
        - text/3/263.md
        - text/3/264.md
        - text/3/265.md
        - text/3/266.md
        - text/3/267.md
        - text/3/268.md
        - text/3/269.md
        - text/3/270.md
        - text/3/271.md
        - text/3/272.md
        - text/3/273.md
        - text/3/274.md
        - text/3/275.md
        - text/3/276.md
        - text/3/277.md
        - text/3/278.md
        - text/3/279.md
        - text/3/280.md
        - text/3/281.md
        - text/3/282.md
        - text/3/283.md
        - text/3/284.md
        - text/3/285.md
        - text/3/286.md
        - text/3/287.md
        - text/3/288.md
        - text/3/289.md
        - text/3/290.md
        - text/3/291.md
        - text/3/292.md
        - text/3/293.md
        - text/3/294.md
        - text/3/295.md
        - text/3/296.md
        - text/3/297.md
        - text/3/298.md
        - text/3/299.md
        - text/3/300.md
        - text/3/301.md
        - text/3/302.md
        - text/3/303.md
        - text/3/304.md
        - text/3/305.md
        - text/3/306.md
        - text/3/307.md
        - text/3/308.md
        - text/3/309.md
        - text/3/310.md
        - text/3/311.md
        - text/3/312.md
        - text/3/313.md
        - text/3/314.md
        - text/3/315.md
        - text/3/316.md
        - text/3/317.md
        - text/3/318.md
        - text/3/319.md
        - text/3/320.md
        - text/3/321.md
        - text/3/322.md
        - text/3/323.md
        - text/3/324.md
        - text/3/325.md
        - text/3/326.md
        - text/3/327.md
        - text/3/328.md
        - text/3/329.md
        - text/3/330.md
        - text/3/331.md
        - text/3/332.md
        - text/3/333.md
        - text/3/334.md
        - text/3/335.md
        - text/3/336.md
        - text/3/337.md
        - text/3/338.md
        - text/3/339.md
        - text/3/340.md
        - text/3/341.md
        - text/3/342.md
        - text/3/343.md
        - text/3/344.md
        - text/3/345.md
        - text/3/346.md
        - text/3/347.md
        - text/3/348.md
        - text/3/349.md
        - text/3/350.md
        - text/3/351.md
        - text/3/352.md
        - text/3/353.md
        - text/3/354.md
        - text/3/355.md
        - text/3/356.md
        - text/3/357.md
        - text/3/358.md
        - text/3/359.md
        - text/3/360.md
        - text/3/361.md
        - text/3/362.md
        - text/3/363.md
        - text/3/364.md
        - text/3/365.md
        - text/3/366.md
        - text/3/367.md
        - text/3/368.md
        - text/3/369.md
        - text/3/370.md
        - text/3/371.md
        - text/3/372.md
        - text/3/373.md
        - text/3/374.md
        - text/3/375.md
        - text/3/376.md
        - text/3/377.md
        - text/3/378.md
        - text/3/379.md
        - text/3/380.md
        - text/3/381.md
        - text/3/382.md
        - text/3/383.md
        - text/3/384.md
        - text/3/385.md
        - text/3/386.md
        - text/3/387.md
        - text/3/388.md
        - text/3/389.md
        - text/3/390.md
        - text/3/391.md
        - text/3/392.md
        - text/3/393.md
        - text/3/394.md
        - text/3/395.md
        - text/3/396.md
        - text/3/397.md
        - text/3/398.md
        - text/3/399.md
        - text/3/400.md
        - text/3/401.md
    - part: text/4/0.md
      chapters:
        - text/4/402.md
        - text/4/403.md
        - text/4/404.md
        - text/4/405.md
        - text/4/406.md
        - text/4/407.md
        - text/4/408.md
        - text/4/409.md
        - text/4/410.md
        - text/4/411.md
        - text/4/412.md
        - text/4/413.md
        - text/4/414.md
        - text/4/415.md
        - text/4/416.md
        - text/4/417.md
        - text/4/418.md
        - text/4/419.md
        - text/4/420.md
        - text/4/421.md
        - text/4/422.md
        - text/4/423.md
        - text/4/424.md
        - text/4/425.md
        - text/4/426.md
        - text/4/427.md
        - text/4/428.md
        - text/4/429.md
        - text/4/430.md
        - text/4/431.md
        - text/4/432.md
        - text/4/433.md
        - text/4/434.md
        - text/4/435.md
        - text/4/436.md
        - text/4/437.md
        - text/4/438.md
        - text/4/439.md
        - text/4/440.md
        - text/4/441.md
        - text/4/442.md
        - text/4/443.md
        - text/4/444.md
        - text/4/445.md
        - text/4/446.md
        - text/4/447.md
        - text/4/448.md
        - text/4/449.md
        - text/4/450.md
        - text/4/451.md
        - text/4/452.md
        - text/4/453.md
        - text/4/454.md
        - text/4/455.md
        - text/4/456.md
        - text/4/457.md
        - text/4/458.md
        - text/4/459.md
        - text/4/460.md
        - text/4/461.md
        - text/4/462.md
        - text/4/463.md
        - text/4/464.md
        - text/4/465.md
        - text/4/466.md
        - text/4/467.md
        - text/4/468.md
        - text/4/469.md
        - text/4/470.md
        - text/4/471.md
        - text/4/472.md
        - text/4/473.md
        - text/4/474.md
        - text/4/475.md
        - text/4/476.md
        - text/4/477.md
        - text/4/478.md
        - text/4/479.md
        - text/4/480.md
        - text/4/481.md
        - text/4/482.md
        - text/4/483.md
        - text/4/484.md
        - text/4/485.md
        - text/4/486.md
        - text/4/487.md
        - text/4/488.md
        - text/4/489.md
        - text/4/490.md
        - text/4/491.md
        - text/4/492.md
        - text/4/493.md
        - text/4/494.md
        - text/4/495.md
        - text/4/496.md
        - text/4/497.md
        - text/4/498.md
        - text/4/499.md
        - text/4/500.md
        - text/4/501.md
        - text/4/502.md
        - text/4/503.md
        - text/4/504.md
        - text/4/505.md
        - text/4/506.md
        - text/4/507.md
        - text/4/508.md
        - text/4/509.md
        - text/4/510.md
        - text/4/511.md
        - text/4/512.md
        - text/4/513.md
        - text/4/514.md
        - text/4/515.md
        - text/4/516.md
        - text/4/517.md
        - text/4/518.md
        - text/4/519.md
        - text/4/520.md
        - text/4/521.md
        - text/4/522.md
        - text/4/523.md
        - text/4/524.md
        - text/4/525.md
        - text/4/526.md
        - text/4/527.md
        - text/4/528.md
        - text/4/529.md
        - text/4/530.md
        - text/4/531.md
        - text/4/532.md
        - text/4/533.md
        - text/4/534.md
        - text/4/535.md
        - text/4/536.md
        - text/4/537.md
        - text/4/538.md
        - text/4/539.md
        - text/4/540.md
        - text/4/541.md
        - text/4/542.md
        - text/4/543.md
        - text/4/544.md
        - text/4/545.md
        - text/4/546.md
        - text/4/547.md
        - text/4/548.md
        - text/4/549.md
        - text/4/550.md
        - text/4/551.md
        - text/4/552.md
        - text/4/553.md
        - text/4/554.md
        - text/4/555.md
        - text/4/556.md
        - text/4/557.md
        - text/4/558.md
        - text/4/559.md
        - text/4/560.md
        - text/4/561.md
        - text/4/562.md
        - text/4/563.md
        - text/4/564.md
        - text/4/565.md
        - text/4/566.md
        - text/4/567.md
        - text/4/568.md
        - text/4/569.md
        - text/4/570.md
        - text/4/571.md
        - text/4/572.md
        - text/4/573.md
        - text/4/574.md
        - text/4/575.md
        - text/4/576.md
        - text/4/577.md
        - text/4/578.md
        - text/4/579.md
        - text/4/580.md
        - text/4/581.md
        - text/4/582.md
        - text/4/583.md
        - text/4/584.md
        - text/4/585.md
        - text/4/586.md
        - text/4/587.md
        - text/4/588.md
        - text/4/589.md
        - text/4/590.md
        - text/4/591.md
        - text/4/592.md
        - text/4/593.md
        - text/4/594.md
        - text/4/595.md
        - text/4/596.md
        - text/4/597.md
        - text/4/598.md
        - text/4/599.md
        - text/4/600.md
        - text/4/601.md
        - text/4/602.md
    - part: text/4.1/0.md
      chapters:
        - text/4.1/1.md
        - text/4.1/2.md
        - text/4.1/3.md
        - text/4.1/4.md
        - text/4.1/5.md
        - text/4.1/6.md
        - text/4.1/7.md
        - text/4.1/8.md
        - text/4.1/9.md
        - text/4.1/10.md
        - text/4.1/11.md
        - text/4.1/12.md
        - text/4.1/13.md
        - text/4.1/14.md
        - text/4.1/15.md
        - text/4.1/16.md
        - text/4.1/17.md
        - text/4.1/18.md
        - text/4.1/19.md
        - text/4.1/20.md
        - text/4.1/21.md
        - text/4.1/22.md
        - text/4.1/23.md
        - text/4.1/24.md
        - text/4.1/25.md
        - text/4.1/26.md
        - text/4.1/27.md
        - text/4.1/28.md
        - text/4.1/29.md
        - text/4.1/30.md
        - text/4.1/31.md
        - text/4.1/32.md
        - text/4.1/33.md
        - text/4.1/34.md
    - part: text/5/0.md
      chapters:
        - text/5/603.md
        - text/5/604.md
        - text/5/605.md
        - text/5/606.md
        - text/5/607.md
        - text/5/608.md
        - text/5/609.md
        - text/5/610.md
        - text/5/611.md
        - text/5/612.md
        - text/5/613.md
        - text/5/614.md
        - text/5/615.md
        - text/5/616.md
        - text/5/617.md
        - text/5/618.md
        - text/5/619.md
        - text/5/620.md
        - text/5/621.md
        - text/5/622.md
        - text/5/623.md
        - text/5/624.md
        - text/5/625.md
        - text/5/626.md
        - text/5/627.md
        - text/5/628.md
        - text/5/629.md
        - text/5/630.md
        - text/5/631.md
        - text/5/632.md
        - text/5/633.md
        - text/5/634.md
        - text/5/635.md
        - text/5/636.md
        - text/5/637.md
        - text/5/638.md
        - text/5/639.md
        - text/5/640.md
        - text/5/641.md
        - text/5/642.md
        - text/5/643.md
        - text/5/644.md
        - text/5/645.md
        - text/5/646.md
        - text/5/647.md
        - text/5/648.md
        - text/5/649.md
        - text/5/650.md
        - text/5/651.md
        - text/5/652.md
        - text/5/653.md
        - text/5/654.md
        - text/5/655.md
        - text/5/656.md
        - text/5/657.md
        - text/5/658.md
        - text/5/659.md
        - text/5/660.md
        - text/5/661.md
        - text/5/662.md
        - text/5/663.md
        - text/5/664.md
        - text/5/665.md
        - text/5/666.md
        - text/5/667.md
    - part: text/6/0.md
      chapters:
        - text/6/1.md
    - part: text/7/0.md
      chapters:
        - text/7/1.md
        - text/7/2.md
        - text/7/3.md
        - text/7/4.md
        - text/7/5.md
        - text/7/6.md
        - text/7/7.md
        - text/7/8.md
    - part: text/8/0.md
      chapters:
        - text/8/1.md
        - text/8/2.md
        - text/8/3.md
        - text/8/4.md
        - text/8/5.md
        - text/8/6.md
        - text/8/7.md
        - text/8/8.md
        - text/8/9.md
        - text/8/10.md
        - text/8/11.md
        - text/8/12.md
        - text/8/13.md
        - text/8/14.md
        - text/8/15.md
        - text/8/16.md
        - text/8/17.md
        - text/8/18.md
        - text/8/19.md
        - text/8/20.md
        - text/8/21.md
        - text/8/22.md
        - text/8/23.md
        - text/8/24.md
        - text/8/25.md
        - text/8/26.md
        - text/8/27.md
    - part: text/9/0.md
      chapters:
        - text/9/1.md
        - text/9/2.md
        - text/9/3.md
        - text/9/4.md
        - text/9/5.md
        - text/9/6.md
        - text/9/7.md
        - text/9/8.md
    - text/10/1.md
