name: Deploy

on:
  push:
  workflow_dispatch:

permissions:
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.0
      - name: Download ebook-convert
        uses: robinraju/release-downloader@v1.8
        with:
          repository: "kovidgoyal/calibre"
          latest: true
          fileName: "calibre-*-x86_64.txz"
      - name: Extract ebook-convert
        run: tar -xf calibre-*-x86_64.txz
      - name: Install dependencies
        run: npm install
      - name: Build static website
        run: npx honkit build
      - name: Build ePub
        run: npx honkit epub ./ ./药娘的天空.epub
      - name: Upload ePub
        uses: actions/upload-artifact@v3.1.3
        with:
          name: ePub
          path: ./药娘的天空.epub

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload Pages content
        uses: actions/upload-pages-artifact@v2
        with:
          path: "_book/"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
